spring:
  application:
    name: backend-sidecar-demo
  profiles:
    active: dev


---
spring:
  profiles: dev

server:
  port: 8209

eureka:
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://admin:123456@127.0.0.1:8100/eureka/

sidecar:
  port: 3800
  health-uri: http://127.0.0.1:${sidecar.port}/health


---
spring:
  profiles: prod

server:
  port: 8209

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://admin:123456@192.168.1.221:8100/eureka/
      defaultZone: ${EUREKA_SERVICE_URL:http://admin:123456@127.0.0.1:8100}/eureka/

sidecar:
  port: 3800
  health-uri: http://127.0.0.1:${sidecar.port}/health




