spring:
  application:
    name: backend-file
  security:
    user:
      name: admin
      password: 123456
  profiles:
    active: dev

  datasource:
    autoReconnect: true
    autoReconnectForPools: true
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.7.102:3305/fosseye?characterEncoding=utf-8
    username: root
    password: 123456

  jpa:
    open-in-view: true
    show-sql: true
---
spring:
  profiles: dev

server:
  port: 8202

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://admin:123456@127.0.0.1:8100/eureka/
      defaultZone: ${EUREKA_SERVICE_URL:http://admin:123456@127.0.0.1:8100}/eureka/

file_path: C:\TC-WORK\upload
---
spring:
  profiles: prod

server:
  port: 8202

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    hostname: 127.0.0.1
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      #defaultZone: http://admin:123456@127.0.0.1:8100/eureka/
      defaultZone: ${EUREKA_SERVICE_URL:http://admin:123456@192.168.1.228:8100}/eureka/




